name: Roslyn Analyzers CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory structure (for debugging)
      run: |
        ls -R
	
	- name: Set up Unity
      uses: game-ci/unity-action@v2
      with:
        unityVersion: 2022.3.48f1

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Install dependencies
      working-directory: "CPSC 362 Group Project V1" 
      run: |
        ls
        dotnet restore "CPSC 362 Group Project V1.sln" 

    - name: Build and run Roslyn analyzers
      working-directory: "CPSC 362 Group Project V1" 
      run: unity -projectPath "CPSC-362-Group-Project/CPSC 362 Group Project V1" -batchmode -nographics -quit -logFile -buildTarget StandaloneWindows64