name: Unity Roslyn Analyzer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Roslyn Analyzers on .NET Framework
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install NuGet CLI (if necessary)
      - name: Install NuGet CLI
        run: choco install nuget.commandline -y

      # List files in the repository (debugging step)
      - name: List repository files
        run: dir

      # Restore dependencies using MSBuild
      - name: Restore dependencies
        run: msbuild ./CPSC-362-Group-Project/CPSC 362 Group Project V1/CPSC 362 Group Project V1.sln /t:Restore

      # Run Roslyn analyzers
      - name: Build and Lint Project
        run: msbuild ./CPSC-362-Group-Project/CPSC 362 Group Project V1/CPSC 362 Group Project V1.sln /p:RunAnalyzers=true /p:Configuration=Release /warnaserror