name: Unity Roslyn Analyzer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Unity in Batch Mode
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Unity using Unity Hub
      - name: Install Unity Hub
        run: |
          choco install unity-hub

      - name: Install Unity
        run: |
          unity-hub --headless install --version 2022.3.48f1

      # Run Unity in batch mode to call the static method 'Build.PerformLinting'
      - name: Run Unity batch mode
        run: |
          "C:\Program Files\Unity\Hub\Editor\2022.3.48f1\Editor\Unity.exe" -batchmode -projectPath "./CPSC 362 Group Project V1" -quit -executeMethod Build.PerformLinting
