name: Unity Roslyn Analyzer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Unity in Batch Mode
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Unity
      - name: Setup Unity
        uses: unity-action/setup@v2
        with:
          version: '2022.3.48f1'  # Specify your Unity version

      # List files in the subfolder (to confirm the path to the .sln file)
      - name: List files in subfolder
        run: dir "./CPSC 362 Group Project V1"

      # Run Unity batch mode to call the static method 'Build.PerformLinting'
      - name: Run Unity batch mode to execute linting
        run: |
          Unity.exe -batchmode -projectPath "./CPSC 362 Group Project V1" -quit -executeMethod Build.PerformLinting