name: Unity Roslyn Analyzer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Roslyn Analyzers
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET (required for Roslyn analyzers)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.0  # Specify the required .NET version for your Unity project

      # Restore NuGet dependencies
      - name: Restore dependencies
        run: dotnet restore ./CPSC-362-Group-Project/CPSC 362 Group Project V1.sln

      # Run Roslyn analyzers
      - name: Run Roslyn Analyzer
        run: dotnet build ./CPSC-362-Group-Project/CPSC 362 Group Project V1.sln --no-restore -warnaserror
