name: Unity Roslyn Analyzer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Roslyn Analyzers on .NET Framework
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Visual Studio (required for .NET Framework projects)
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages
      - name: Restore dependencies
        run: nuget restore ./CPSC-362-Group-Project/CPSC 362 Group Project V1.sln

      # Run Roslyn analyzers using MSBuild
      - name: Build and Lint Project
        run: msbuild ./CPSC-362-Group-Project/CPSC 362 Group Project V1.sln /p:RunAnalyzers=true /p:Configuration=Release /warnaserror