name: Unity Roslyn Analyzer

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Build Unity Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Unity using game-ci/unity-setup
      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.48f1 # Match this to your Unity project version
          activationMode: manual
          license: ${{ secrets.UNITY_LICENSE }}

      # Restore dependencies (if applicable)
      - name: Restore dependencies
        run: unity -quit -batchmode -logfile -projectPath "./CPSC 362 Group Project V1" -executeMethod UnityEditor.Compilation.CompilationPipeline

      # Run Roslyn analyzers (optional, if analyzers are part of the Unity project)
      - name: Run Roslyn Analyzer (optional)
        run: msbuild "./CPSC 362 Group Project V1/CPSC 362 Group Project V1.sln" /p:RunAnalyzers=true /warnaserror

      # Build the project
      - name: Build Unity Project
        run: unity -quit -batchmode -logfile -projectPath "./CPSC 362 Group Project V1" -buildTarget StandaloneWindows64 -outputDirectory Build
