name: Unity Roslyn Analyzer
name: Code Linting for Unity Project

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Unity in Batch Mode
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Unity using Unity Hub
      - name: Install Unity
        run: |
          choco install unity --version=2022.3.48f1 --package-parameters "--accept-license --no-progress"
      
      # Set Unity environment variables (if needed)
      - name: Set up Unity environment
        run: |
          setx UNITY_PATH "C:\Program Files\Unity\Hub\Editor\2021.3.17f1\Editor"

      # List files in the subfolder (to confirm the path to the .sln file)
      - name: List files in subfolder
        run: dir "./CPSC 362 Group Project V1"

      # Run Unity in batch mode to call the static method 'Build.PerformLinting'
      - name: Run Unity batch mode to execute linting
        run: |
          "C:\Program Files\Unity\Hub\Editor\2021.3.17f1\Editor\Unity.exe" -batchmode -projectPath "./CPSC 362 Group Project V1" -quit -executeMethod Build.PerformLinting